### ISSUE TITLE
Adicionar data para abertura das inscrições

### ISSUE THREAD

**Issue by RodolfoLemes** [RodolfoLemes/seel-backend#3]
Para impedir o acesso a rota de inscrições, adicionar um tratamento (em um `middleware` talvez)  para impedir o acesso na rota.

Colocar no arquivo `.env` a data de início.

**Comment by leonichel** [comment]
Boa

**Comment by RodolfoLemes** [comment]
> Boa

Ajuda ai, cria uma PR para arrumar isso.
